kind: pipeline
type: docker
name: default
steps:
  - name: install
    image: node:10
    commands:
      - "npm install --registry=https://registry.npm.taobao.org"
      - "./node_modules/.bin/hexo deploy"

  - name: check file
    image: alpine
    commands:
      - ls 

  - name: build image
    image: docker:18.06.3-ce
    commands:
      - "docker rm -f hexo || :"
      - docker build -t hexo-blog . 
      - docker run --network=website_default -itd --name=hexo --label-file ./traefik-label hexo-blog
    volumes:
    - name: dockersock
      path: /var/run/docker.sock




volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock