kind: pipeline
type: docker
name: default
steps:

  - name: install
    image: node
    commands:
      - "npm install --registry=https://registry.npm.taobao.org"
      - "hexo deploy"

  - name: build image
    image: docker:18.06.3-ce
    commands:
      - docker build -t hexo-blog . 
      - docker run --network=website_default --label-file ./traefik-label hexo-blog
